name: 幻水総選挙2021（フロントエンド）

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  gensosenkyo_2021_frontend:
    name: 幻水総選挙2021（フロントエンド）
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: ['14.x', '16.x', '18.x']
        node-version: ['14.17.0']
    steps:
      - name: コードをチェックアウトする
        uses: actions/checkout@v3
      - name: simple-git-hooks 用のダミーディレクトリを作成
        run: |
          mkdir .git
          mkdir .git/hooks
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: $ yarn install を行う
        run: |
          yarn install
      - name: $ yarn build が通るかチェックする
        run: |
          yarn build
      - name: Webブラウザで JavaScript が解釈されて期待どおりに表示されているかを簡易チェックする
        run: |
          yarn add --dev capture-website --unsafe-perm
          apt install -y tesseract-ocr libtesseract-dev tesseract-ocr-jpn fonts-migmix

          npx http-server build/ -p 8080 &
          npx capture-website http://localhost:8080 --output=screenshot.png
          tesseract screenshot.png screenshot_ocr -l jpn txt

          # 文字列が存在しない場合はエラーを返すので CI が落ちる
          grep -q "総選挙" screenshot_ocr.txt
