on: [push]
name: 幻水総選挙2021（フロントエンド）
jobs:
  suikoden_election_2021_database_github_actions:
    name: GitHub Actions CI
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0
    steps:
      - uses: actions/checkout@v2
      - name: simple-git-hooks 用のダミーディレクトリを作成
        run: |
          mkdir .git
          mkdir .git/hooks
      - name: Yarn のインストールを行う
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          apt update
          apt install -y yarn
      - name: Yarn のキャッシュのパスを取得する
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn のキャッシュファイルを取得する
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: $ yarn install を行う
        run: |
          yarn install
      - name: $ yarn build が通るかチェックする
        run: |
          yarn build
      - name: Webブラウザで JavaScript が解釈されて期待どおりに表示されているかを簡易チェックする
        run: |
          npm install -g capture-website --unsafe-perm
          apt install -y tesseract-ocr libtesseract-dev tesseract-ocr-jpn fonts-migmix

          npx http-server build/ -p 8080 &
          npx capture-website http://localhost:8080 --output=screenshot.png
          tesseract screenshot.png screenshot_ocr -l jpn txt

          # 文字列が存在しない場合はエラーを返すので CI が落ちる
          grep -q "総選挙" screenshot_ocr.txt
