name: git-pr-release による release PR 作成

on:
  push:
    branches:
      - gpr_test

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Ruby のセットアップ
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.1

    - name: git-pr-release を用いて自動でプルリクエストを作成する
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: main
        GIT_PR_RELEASE_BRANCH_STAGING: gpr_test
        GIT_PR_RELEASE_LABELS: release
      run: |
        gem install -N git-pr-release
        git-pr-release --no-fetch
